/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-06-29 15:34:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.system.page.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/tlds/fn.tld", Long.valueOf(1427989084000L));
    _jspx_dependants.put("/WEB-INF/tlds/spring-security.tld", Long.valueOf(1427989084000L));
    _jspx_dependants.put("/system/page/main/../../../common/page/common.jsp", Long.valueOf(1427989102000L));
    _jspx_dependants.put("/WEB-INF/tlds/dict.tld", Long.valueOf(1427989084000L));
    _jspx_dependants.put("/WEB-INF/tlds/fmt.tld", Long.valueOf(1427989084000L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1427989084000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fauth_005fscript_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fauth_005fscript_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fauth_005fscript_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/css/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/css/niceValidate/jquery.validator.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/css/themes/default/easyui.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/jquery.validator.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/zh_CN.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- my97日历空控件 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/js/language/ecs_zh.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/js/easyui-extend.js\"></script>\r\n");
      out.write("<!-- 加入js权限校验 用法 var auth = new Auth(); auth.access('权限编码'); -->\r\n");
      if (_jspx_meth_auth_005fscript_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>ECS后台管理</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/js/ECSTab.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/dateUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/js/resource/resourceTreeConvert.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/js/index/index.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/js/index/userInfo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.STYLE2 {color: #43860c; font-size: 12px; }\r\n");
      out.write("\ta:link {font-size:12px; text-decoration:none; color:#43860c;}\r\n");
      out.write("\ta:visited {font-size:12px; text-decoration:none; color:#43860c;}\r\n");
      out.write("\ta:hover{font-size:12px; text-decoration:none; color:#FF0000;}\r\n");
      out.write("\t.tabLeft{\r\n");
      out.write("\t\ttext-align: right;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(\"document\").ready(function(){\r\n");
      out.write("\t\tvar dateUtil = new DateUtil();\r\n");
      out.write("\t\tvar format = document.getElementById(\"time\").innerHTML;\r\n");
      out.write("\t\tdocument.getElementById(\"time\").innerHTML = dateUtil.format(null,format);\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div data-options=\"region:'north',border:false\" style=\"height:70px;background-color: #90C94B;\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"table-layout:fixed;\">\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td height=\"9\" style=\"line-height:9px; background-image:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_04.gif)\">\r\n");
      out.write("\t\t\t    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td width=\"97\" height=\"9\" background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_01.gif\">&nbsp;</td>\r\n");
      out.write("\t\t\t        <td>&nbsp;</td>\r\n");
      out.write("\t\t\t        <td>&nbsp;</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t\t    </table>\r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td height=\"47\" background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_09.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <td width=\"38\" height=\"47\" background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_06.gif\">&nbsp;</td>\r\n");
      out.write("\t\t        <td width=\"59\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t          <tr>\r\n");
      out.write("\t\t            <td height=\"29\" background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_07.gif\">&nbsp;</td>\r\n");
      out.write("\t\t          </tr>\r\n");
      out.write("\t\t          <tr>\r\n");
      out.write("\t\t            <td height=\"18\" background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_14.gif\">\r\n");
      out.write("\t\t\t            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"table-layout:fixed;\">\r\n");
      out.write("\t\t\t              <tr>\r\n");
      out.write("\t\t\t                <td  style=\"width:1px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t                <td ><span class=\"STYLE1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.geUser.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t              </tr>\r\n");
      out.write("\t\t\t            </table>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t          </tr>\r\n");
      out.write("\t\t        </table></td>\r\n");
      out.write("\t\t        <td width=\"155\" background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_08.gif\">&nbsp;</td>\r\n");
      out.write("\t\t        <td>\r\n");
      out.write("\t\t\t        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t          <tr>\r\n");
      out.write("\t\t\t            <td height=\"23\" valign=\"bottom\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_12.gif\" width=\"367\" height=\"23\" border=\"0\" usemap=\"#Map\" /></td>\r\n");
      out.write("\t\t\t          </tr>\r\n");
      out.write("\t\t\t        </table>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t        <td width=\"200\" background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_11.gif\">\r\n");
      out.write("\t\t\t        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t          <tr>\r\n");
      out.write("\t\t\t            <td width=\"11%\" height=\"23\">&nbsp;</td>\r\n");
      out.write("\t\t\t            <td width=\"89%\" valign=\"bottom\"><span class=\"STYLE1\" id=\"time\">日期：yyyy年M月d日 星期W</span></td>\r\n");
      out.write("\t\t\t          </tr>\r\n");
      out.write("\t\t\t        </table>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t    </table>\r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td height=\"5\" style=\"line-height:5px; background-image:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_18.gif)\">\r\n");
      out.write("\t\t\t    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td width=\"180\" background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_16.gif\"  style=\"line-height:5px;\">&nbsp;</td>\r\n");
      out.write("\t\t\t        <td>&nbsp;</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t\t    </table>\r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<map name=\"Map\" id=\"Map\">\r\n");
      out.write("\t\t\t<area shape=\"rect\" coords=\"3,1,49,22\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t<area shape=\"rect\" coords=\"52,2,95,21\" href=\"#\" onclick=\"index.goBack();\"/>\r\n");
      out.write("\t\t\t<area shape=\"rect\" coords=\"102,2,144,21\" href=\"#\" onclick=\"index.goTab();\" />\r\n");
      out.write("\t\t\t<area shape=\"rect\" coords=\"150,1,197,22\" href=\"#\" onclick=\"index.flushTab();\" />\r\n");
      out.write("\t\t\t<area shape=\"rect\" coords=\"210,2,304,20\" href=\"#\" onclick=\"index.alterInfo('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.geUser.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\" />\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<area shape=\"rect\" coords=\"314,1,361,23\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/logout\" />\r\n");
      out.write("\t\t</map>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'south',border:false\" style=\"height:25px;background-color: #90C94B;\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td height=\"24\" background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_47.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <td width=\"29\" height=\"24\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_45.gif\" width=\"29\" height=\"24\" /></td>\r\n");
      out.write("\t\t        <td>\r\n");
      out.write("\t\t\t        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t          <tr>\r\n");
      out.write("\t\t\t            <td width=\"369\"><span class=\"STYLE1\">中科软ECS后台管理平台 版本 V5.0</span></td>\r\n");
      out.write("\t\t\t            <td width=\"814\" class=\"STYLE1\">&nbsp;</td>\r\n");
      out.write("\t\t\t            <td width=\"185\" nowrap=\"nowrap\" class=\"STYLE1\"><div align=\"center\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_51.gif\" width=\"12\" height=\"12\" /> 如有疑问请与技术人员联系</div></td>\r\n");
      out.write("\t\t\t          </tr>\r\n");
      out.write("\t\t\t        </table>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t        <td width=\"14\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/images/main_49.gif\" width=\"14\" height=\"24\" /></td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t    </table></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'west',split:false,title:'管理选项'\" style=\"width:230px;\">\r\n");
      out.write("\t\t<div class=\"easyui-layout\" style=\"width:227px;border-bottom: 3px solid #90C94B;\" data-options=\"fit:true\">\r\n");
      out.write("\t\t\t<div data-options=\"region:'north',border:false\" style=\"height:70px;\" data-options=\"fit:true\">\r\n");
      out.write("\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div data-options=\"region:'center',border:false,title:' '\" style=\"vertical-align:0px;\" data-options=\"fit:true\">\r\n");
      out.write("\t\t\t\t<div style=\"padding-top: 10px;\" >\r\n");
      out.write("\t\t\t\t\t<div id=\"menuNav\" ></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'center'\" style=\"vertical-align:0px;\">\r\n");
      out.write("\t\t<div class=\"easyui-tabs\" data-options=\"fit:true\" id=\"mainTab\" >\r\n");
      out.write("\t\t\t<div title=\"首页\" style=\"padding:10px\" id=\"menuNav_Home\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table class=\"easyui-propertygrid\" data-options=\"title:'系统信息',scrollbarSize:0,fitColumns:true,fit:true\">   \r\n");
      out.write("\t\t\t    <thead>   \r\n");
      out.write("\t\t\t        <tr>   \r\n");
      out.write("\t\t\t            <th data-options=\"title:'系统信息',field:'name'\">系统信息</th>   \r\n");
      out.write("\t\t\t            <th >系统值</th>   \r\n");
      out.write("\t\t\t        </tr>   \r\n");
      out.write("\t\t\t    </thead>   \r\n");
      out.write("\t\t\t    <tbody>   \r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t        \t<td></td>\r\n");
      out.write("\t\t\t            <td>操作系统</td>\r\n");
      out.write("\t\t\t            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${osName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>   \r\n");
      out.write("\t\t\t        </tr> \r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t        \t<td></td>\r\n");
      out.write("\t\t\t            <td>HTTP服务器</td>\r\n");
      out.write("\t\t\t            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serverInfo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>   \r\n");
      out.write("\t\t\t        </tr> \r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t        \t<td></td>\r\n");
      out.write("\t\t\t            <td>虚拟机总内存</td>\r\n");
      out.write("\t\t\t            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>   \r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t        \t<td></td>\r\n");
      out.write("\t\t\t            <td>虚拟机空闲内存</td>\r\n");
      out.write("\t\t\t            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${free }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>   \r\n");
      out.write("\t\t\t        </tr>     \r\n");
      out.write("\t\t\t        ");
      out.write("\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t        \t<td></td>\r\n");
      out.write("\t\t\t            <td>项目部署路径</td>\r\n");
      out.write("\t\t\t            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${deployPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>   \r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t        \t<td></td>\r\n");
      out.write("\t\t\t            <td>JDK版本</td>\r\n");
      out.write("\t\t\t            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vmVersion }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>   \r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t    </tbody>   \r\n");
      out.write("\t\t\t</table>  \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"alterUserInfo_windows\" style=\"display: none;background-color:white ; font-size: 15px; padding: 10px;overflow:hidden;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\tvar index = new Index();\r\n");
      out.write("\t\tindex.ctx= '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\tvar data = eval('('+'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${childResources}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'+')');\r\n");
      out.write("\t\t//alert(data.toJSONString());\r\n");
      out.write("\t\t\t$('#menuNav').tree({    \r\n");
      out.write("\t\t\tdata: convert(data),\r\n");
      out.write("\t\t\tanimate:true,\r\n");
      out.write("\t\t\tlines:true,\r\n");
      out.write("\t\t\tonClick:function(node){\r\n");
      out.write("\t\t\t\tvar tid = node.id;\r\n");
      out.write("\t\t\t\tvar isLeaf = $('#'+tid).tree('isLeaf',node.target); //是否是叶子节点\r\n");
      out.write("\t\t\t\tif(isLeaf){\r\n");
      out.write("\t\t\t\t\tvar title = node.text;\r\n");
      out.write("\t\t\t\t\tvar url = node.attributes.url;\r\n");
      out.write("\t\t\t\t\tvar tab = new ECSTab();\r\n");
      out.write("\t\t\t\t\ttab.addTab(title,tid,url);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /system/page/main/../../../common/page/common.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /system/page/main/../../../common/page/common.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_auth_005fscript_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  auth:script
    cn.com.sinosoft.core.springsecurity.SpringSecurityScriptTag _jspx_th_auth_005fscript_005f0 = (cn.com.sinosoft.core.springsecurity.SpringSecurityScriptTag) _005fjspx_005ftagPool_005fauth_005fscript_005fnobody.get(cn.com.sinosoft.core.springsecurity.SpringSecurityScriptTag.class);
    _jspx_th_auth_005fscript_005f0.setPageContext(_jspx_page_context);
    _jspx_th_auth_005fscript_005f0.setParent(null);
    int _jspx_eval_auth_005fscript_005f0 = _jspx_th_auth_005fscript_005f0.doStartTag();
    if (_jspx_th_auth_005fscript_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fauth_005fscript_005fnobody.reuse(_jspx_th_auth_005fscript_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fauth_005fscript_005fnobody.reuse(_jspx_th_auth_005fscript_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /system/page/main/index.jsp(134,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootResources }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /system/page/main/index.jsp(134,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("resource");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div style=\"width:60px;float: left;padding-left: 12px;\">\r\n");
          out.write("\t\t\t\t\t\t\t<table>\r\n");
          out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"index.choseModel('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resource.resourcesid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resource.geResourcesIcon.resourcesiconpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" name=\"Image1\" width=\"32\"  border=\"0\"  />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"index.choseModel('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resource.resourcesid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resource.resourcesname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
