/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-04-18 06:57:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.icbc.investmentlinked.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cpzx_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/tlds/dict.tld", Long.valueOf(1397242678135L));
    _jspx_dependants.put("/WEB-INF/tlds/fn.tld", Long.valueOf(1397242676826L));
    _jspx_dependants.put("/WEB-INF/tlds/fmt.tld", Long.valueOf(1397242678139L));
    _jspx_dependants.put("/icbc/investmentlinked/page/../../../common/page/common.jsp", Long.valueOf(1397566400044L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1397242678131L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/css/login.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/css/niceValidate/jquery.validator.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/validate/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/validate/additional-methods.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/validate/messages_zh.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/jquery.lightbox_me.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML> \r\n");
      out.write("<html>\r\n");
      out.write("  <head lang=\"en\">\r\n");
      out.write("    \r\n");
      out.write("    <TITLE> 工银安盛人寿保险有限公司</TITLE>\r\n");
      out.write("\t<META name=\"description\" content=\"工银安盛人寿官方网站提供最新公司动态，为您提供有关工银安盛人寿近期新闻信息、活动资讯、产品服务等的第一手资讯\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/js/date/WdatePicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/js/investment.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/js/service.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/js/json2.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/js/up.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/css/styles.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/js/hover/productCenter.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t//左菜单焦点图\r\n");
      out.write("\tvar time=3000;//间隔时间ms\r\n");
      out.write("\tvar num=0;\r\n");
      out.write("\tfunction changeform(){\r\n");
      out.write("\t\tvar f_img_div = document.getElementById(\"f_img\").getElementsByTagName(\"div\");\r\n");
      out.write("\t\tif(num > f_img_div.length-1) num=0;\r\n");
      out.write("\t\tsetfocus(num);\r\n");
      out.write("\t\tnum++;\r\n");
      out.write("\t} \r\n");
      out.write("\tfunction setfocus(id){\r\n");
      out.write("\t\tnum = id;\r\n");
      out.write("\t\tvar f_img_div = document.getElementById(\"f_img\").getElementsByTagName(\"div\");\r\n");
      out.write("\t\tvar layers = f_img_div;\r\n");
      out.write("\t\tvar f_num_a = document.getElementById(\"f_num\").getElementsByTagName(\"a\");\r\n");
      out.write("\t\tvar layernavs = f_num_a;\r\n");
      out.write("\t\tfor(var i=0;i<layers.length;i++){\r\n");
      out.write("\t\t\tif(i==id){\r\n");
      out.write("\t\t\t\tlayernavs[i].style.color=\"#e5242c\";\r\n");
      out.write("\t\t\t\tlayers[i].style.display=\"block\";\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tlayernavs[i].style.color=\"#565656\";\r\n");
      out.write("\t\t\t\tlayers[i].style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} \r\n");
      out.write("\t//setInterval('changeform()',time); //图片轮播\r\n");
      out.write("\t//客服\r\n");
      out.write("\tfunction onlineAsk() {\r\n");
      out.write("\t\tvar url = 'http://care.live800.com/live800/chatClient/chatbox.jsp?companyID=233797&configID=114975&jid=6580108305';\r\n");
      out.write("\t\t//var userName =  '';\r\n");
      out.write("\t\t//var info = escape('name=' + userName + '&memo=');\r\n");
      out.write("\t\tsetTimeout(function () {\r\n");
      out.write("\t\t  window.open(url + '&info=userId%3D0%26name%3D%26memo%3D', 'chatbox105517', 'toolbar=0,scrollbars=0,location=0,menubar=0,resizable=1,width=570,height=424');\r\n");
      out.write("\t\t}, 500);\r\n");
      out.write("\t } \r\n");
      out.write("\r\n");
      out.write("\tfunction imgLink(productCode){\r\n");
      out.write("\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=\"+productCode;\r\n");
      out.write("\t}\r\n");
      out.write("\t//跳转产品\r\n");
      out.write("\tfunction img1(){\r\n");
      out.write("\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=NPACA\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction img2(){\r\n");
      out.write("\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=BCIB\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction img3(){\r\n");
      out.write("\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=FTA\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction img4(){\r\n");
      out.write("\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=JEB\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction img5(){\r\n");
      out.write("\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=BSPG7\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction img6(){\r\n");
      out.write("\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=AA\";\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body style=\"margin: 0 auto\">\r\n");
      out.write("  \t<!--引入header页面  -->\r\n");
      out.write("  \t<div class=\"content\">\r\n");
      out.write("   \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("   \t\r\n");
      out.write("   \t<!-- body -->\r\n");
      out.write("   \t<div style=\"background-color: white;height:1250px;width: 985px\">\r\n");
      out.write("   \t\t<div style=\"height:46px ;background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/hhh1.gif');background-repeat: no-repeat;line-height: 46px;padding-left: 40px\">\r\n");
      out.write("   \t\t<span style=\"color: 7f7f7f;font-size: 12px;\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("   \t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\" class=\"at\">在线商城首页</a>&nbsp;&gt;&nbsp;\r\n");
      out.write("   \t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/allProduct\" class=\"at\">在线购买</a></span>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<!-- 上半部分 -->\r\n");
      out.write("   \t\t   \t\t<div>\r\n");
      out.write("\t   \t\t<div class=\"leftPanel01\" id=\"f_num\">\r\n");
      out.write("\t     \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=BCIB\" onmouseover=\"javascript:setfocus(0);\" style=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/product/leftBg0.gif) no-repeat;height:45px;margin-top:16px;padding-top: 22px;\">健康保险</a>\r\n");
      out.write("\t     \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=FTA\" onmouseover=\"javascript:setfocus(1);\" style=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/product/leftBg1.gif) no-repeat;height:45px;padding-top: 20px;\">意外保险</a>\r\n");
      out.write("\t     \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=BSPG7\" onmouseover=\"javascript:setfocus(2);\" style=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/product/leftBg2.gif) no-repeat;height:42px;padding-top: 20px;\">理财保险</a>\r\n");
      out.write("\t     \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=NPACA\" onmouseover=\"javascript:setfocus(3);\" style=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/product/leftBg3.gif) no-repeat;height:45px;padding-top: 20px;\">养老保险</a>\r\n");
      out.write("\t     \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/productCesuan?productcode=JEB\" onmouseover=\"javascript:setfocus(4);\" style=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/product/leftBg4.gif) no-repeat;height:45px;padding-top: 20px;\">少儿保险</a>\r\n");
      out.write("\t     \t\t\t<a href=\"#\" onmouseover=\"javascript:setfocus(5);\" style=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/product/leftBg5.gif) no-repeat;height:45px;padding-top: 20px;\">女性保险</a>\r\n");
      out.write("\t     \t</div>\r\n");
      out.write("\t     \t<div id=\"f_img\">\r\n");
      out.write("\t\t     \t<div id=\"box00\" style=\"background: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/leftPa00.jpg) no-repeat;width:712px;height:406px;float:left;margin-left:2px;\" onclick=\"img2();\">\r\n");
      out.write("\t\t     \t\t<!--<span style=\"display:block; font-size: 14px;font-weight: bold;margin-top: 355px;margin-left: 50px;color: #ffffff;height: 6px;\">养老保险 </span><br/>\r\n");
      out.write("\t\t   \t\t\t<span  style=\"font-size: 12px;margin-left: 50px;color: #ffffff\">3.8活动|万里通积分当钱花3.8活动|万里通积分当钱花3.8活动|万里通积分当钱</span>-->\r\n");
      out.write("\t\t     \t</div>\r\n");
      out.write("\t\t     \t<div id=\"box01\" style=\"display:none;background: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/leftPa01.jpg) no-repeat;width:712px;height:406px;float:left;margin-left:2px;\" onclick=\"img3();\">\r\n");
      out.write("\t\t     \t\t<!--<span style=\"display:block; font-size: 14px;font-weight: bold;margin-top: 355px;margin-left: 50px;color: #ffffff;height: 6px;\">养老保险 </span><br/>\r\n");
      out.write("\t\t   \t\t\t<span  style=\"font-size: 12px;margin-left: 50px;color: #ffffff\">3.8活动|万里通积分当钱花3.8活动|万里通积分当钱花3.8活动|万里通积分当钱</span>-->\r\n");
      out.write("\t\t     \t</div>\t\r\n");
      out.write("\t\t     \t<div id=\"box02\" style=\"display:none;background: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/leftPa02.jpg) no-repeat;width:712px;height:406px;float:left;margin-left:2px;\" onclick=\"img5();\">\r\n");
      out.write("\t\t     \t\t<!--<span style=\"display:block; font-size: 14px;font-weight: bold;margin-top: 355px;margin-left: 50px;color: #ffffff;height: 6px;\">养老保险 </span><br/>\r\n");
      out.write("\t\t   \t\t\t<span  style=\"font-size: 12px;margin-left: 50px;color: #ffffff\">3.8活动|万里通积分当钱花3.8活动|万里通积分当钱花3.8活动|万里通积分当钱</span>-->\r\n");
      out.write("\t\t     \t</div>\t\r\n");
      out.write("\t\t     \t<div id=\"box03\" style=\"display:none;background: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/leftPa04.jpg) no-repeat;width:712px;height:406px;float:left;margin-left:2px;\" onclick=\"img1();\">\r\n");
      out.write("\t\t     \t\t<!--<span style=\"display:block; font-size: 14px;font-weight: bold;margin-top: 355px;margin-left: 50px;color: #ffffff;height: 6px;\">养老保险 </span><br/>\r\n");
      out.write("\t\t   \t\t\t<span  style=\"font-size: 12px;margin-left: 50px;color: #ffffff\">3.8活动|万里通积分当钱花3.8活动|万里通积分当钱花3.8活动|万里通积分当钱</span>-->\r\n");
      out.write("\t\t     \t</div>\t\r\n");
      out.write("\t\t     \t<div id=\"box04\" style=\"display:none;background: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/leftPa03.JPG) no-repeat;width:712px;height:406px;float:left;margin-left:2px;\" onclick=\"img4();\">\r\n");
      out.write("\t\t     \t\t<!--<span style=\"display:block; font-size: 14px;font-weight: bold;margin-top: 355px;margin-left: 50px;color: #ffffff;height: 6px;\">养老保险 </span><br/>\r\n");
      out.write("\t\t   \t\t\t<span  style=\"font-size: 12px;margin-left: 50px;color: #ffffff\">3.8活动|万里通积分当钱花3.8活动|万里通积分当钱花3.8活动|万里通积分当钱</span>-->\r\n");
      out.write("\t\t     \t</div>\t\r\n");
      out.write("\t\t     \t<div id=\"box05\" style=\"display:none;background: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/leftPa05.jpg) no-repeat;width:712px;height:406px;float:left;margin-left:2px;\">\r\n");
      out.write("\t\t     \t\t<!--<span style=\"display:block; font-size: 14px;font-weight: bold;margin-top: 355px;margin-left: 50px;color: #ffffff;height: 6px;\">养老保险 </span><br/>\r\n");
      out.write("\t\t   \t\t\t<span  style=\"font-size: 12px;margin-left: 50px;color: #ffffff\">3.8活动|万里通积分当钱花3.8活动|万里通积分当钱花3.8活动|万里通积分当钱</span>-->\r\n");
      out.write("\t\t     \t</div>\r\n");
      out.write("\t\t     </div>\t\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<!-- 下半部分 -->\r\n");
      out.write("   \t\t<div style=\"float: left;\">\r\n");
      out.write("\t   \t\t<!-- 销售排行 -->\r\n");
      out.write("\t   \t\t<div style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/bg1_03.gif);height:305px;background-repeat: no-repeat;margin-left:30px;padding-top:20px;width:931px;\">\r\n");
      out.write("\t   \t\t\t<p style=\"font-size: 15px;font-weight: bold;font-family:微软雅黑; color: #da3b3d;margin-left: 52px;\">热销排行</p>\r\n");
      out.write("\t   \t\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /icbc/investmentlinked/page/cpzx.jsp(134,8) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDto}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /icbc/investmentlinked/page/cpzx.jsp(134,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("policyDtos");
      // /icbc/investmentlinked/page/cpzx.jsp(134,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<div style=\"float:left;width:310px;\">\r\n");
            out.write("\t\t\t\t\t\t\t<div style=\"margin-top: 8px;width:100%;height:130px;margin-left:14px;float:left;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div  class=\"img1\" style=\"background: url(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDtos.productImpagePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(") no-repeat;width:272px;height:135px;float:left;display:inline;margin-right:20px;cursor: pointer;\" onclick=\"imgLink('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDtos.productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("')\"></div>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t<div style=\"float: left;width: 272px;margin-left: 20px;margin-top:20px;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<table>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\" ><a href=\"");
            out.print(request.getContextPath());
            out.write("/icbc/investmentlinked/productCesuan?productcode=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDtos.productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" style=\"font-size: 14px;font-weight: bold;text-decoration:none;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDtos.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr height=\"40px;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\" style=\"font-size: 12px;color: gray;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDtos.productDepict}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr height=\"22px\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-size: 14px;color: red;\">价格：");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDtos.productPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("元起</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td rowspan=\"2\" style=\"text-align: right\"><a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("/icbc/investmentlinked/productCesuan?productcode=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDtos.productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"><img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("/icbc/investmentlinked/images/img07.png\"/></a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"color: lightgray\" >已售出");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDtos.productCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("份</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\r\n");
      out.write("\t   \t\t</div>\r\n");
      out.write("\t   \t\t<!-- 新品上架 \t!-->\r\n");
      out.write("\t   \t\t<div style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/images/bg02.gif');height:305px;background-repeat: no-repeat;margin-left:30px;padding-top:16px;width:931px;\">\r\n");
      out.write("\t   \t\t\t<p style=\"font-size: 15px;font-weight: bold;font-family:微软雅黑; color: #da3b3d;margin-left: 60px;\">最新上架</p>\r\n");
      out.write("\t   \t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /icbc/investmentlinked/page/cpzx.jsp(162,7) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDtoNew}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /icbc/investmentlinked/page/cpzx.jsp(162,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("policyDto");
      // /icbc/investmentlinked/page/cpzx.jsp(162,7) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<div style=\"float:left;width:310px;\">\r\n");
            out.write("\t\t\t\t\t\t\t<div style=\"margin-top: 8px;width:100%;height:130px;margin-left:14px;float:left;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div  class=\"img1\" style=\"background: url(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDto.productImpagePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(") no-repeat;width:272px;height:135px;float:left;display:inline;margin-right:20px;cursor: pointer;\" onclick=\"imgLink('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDto.productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("')\"></div>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t<div style=\"float: left;width: 272px;margin-left: 20px;margin-top:20px;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<table>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\" ><a href=\"");
            out.print(request.getContextPath());
            out.write("/icbc/investmentlinked/productCesuan?productcode=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDto.productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" style=\"font-size: 14px;font-weight: bold;text-decoration:none;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDto.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr height=\"40px;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\" style=\"font-size: 12px;color: gray;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDto.productDepict}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr height=\"22px\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-size: 14px;color: red;\">价格：");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDto.productPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("元起</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td rowspan=\"2\" style=\"text-align: right\"><a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("/icbc/investmentlinked/productCesuan?productcode=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDto.productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"><img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("/icbc/investmentlinked/images/img07.png\"/></a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"color: lightgray\" >已售出");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${policyDto.productCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("份</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      }
      out.write("\r\n");
      out.write("\t   \t\t\t\r\n");
      out.write("\t   \t\t</div>\r\n");
      out.write("\t   \t\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<DIV id=\"homeBanner\" style=\"margin-top:5px; padding: 10px 0px 9px 13px; width: 960px;  overflow: hidden;margin-left:4px;\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "homeBanner.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("</div>\r\n");
      out.write("   \t\t\r\n");
      out.write("<DIV style=\"margin: 23px auto 0px; padding: 0px 0px 23px; width: 985px;\">\r\n");
      out.write("</DIV>\r\n");
      out.write("   \t</div>\r\n");
      out.write("   \t<!-- 引入footer页面 -->\r\n");
      out.write("   \t<div id=\"footerWrapper\" style=\"width: 100%; height:67px;float:left; \" frameborder=\"no\" border=\"0\"  scrolling=\"no\">\r\n");
      out.write("   \t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\t   \t\t\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /icbc/investmentlinked/page/../../../common/page/common.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /icbc/investmentlinked/page/../../../common/page/common.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
