/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-04-11 20:18:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.icbc.investmentlinked.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t<div id=\"footerWrapper\">\r\n");
      out.write("\t\t<div style=\"width: 985px; margin: 0 auto; color: #747474\">\r\n");
      out.write("\t\t\t<div style=\"float: left; line-height: 60px;\">\r\n");
      out.write("\t\t\t\t<a target=\"_self\" href=\"http://www.icbc-axa.com/page/links\"\r\n");
      out.write("\t\t\t\t\trel=\"nofollow\" style=\"text-decoration: none; color: #747474;\">友情链接\r\n");
      out.write("\t\t\t\t</a> <span class=\"divider\"> |</span> <a target=\"_self\"\r\n");
      out.write("\t\t\t\t\thref=\"http://www.icbc-axa.com/page/sitemap\" rel=\"nofollow\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-decoration: none; color: #747474;\">网站地图 </a> <span\r\n");
      out.write("\t\t\t\t\tclass=\"divider\"> |</span> <a target=\"_self\"\r\n");
      out.write("\t\t\t\t\thref=\"http://www.icbc-axa.com/page/antimoneylaundering\"\r\n");
      out.write("\t\t\t\t\trel=\"nofollow\" style=\"text-decoration: none; color: #747474;\">反洗钱规定</a>\r\n");
      out.write("\t\t\t\t<span class=\"divider\"> |</span> <a target=\"_self\"\r\n");
      out.write("\t\t\t\t\thref=\"http://www.icbc-axa.com/page/legal\" rel=\"nofollow\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-decoration: none; color: #747474;\">法律条款</a> <span\r\n");
      out.write("\t\t\t\t\tclass=\"divider\"> |</span> <a target=\"_self\"\r\n");
      out.write("\t\t\t\t\thref=\"http://www.icbc-axa.com/page/privacy\" rel=\"nofollow\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-decoration: none; color: #747474;\">隐私权声明</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tstyle=\"float: left; padding-left: 0px; padding-right: 0px; width: 410px; padding-top: 10px;\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a\r\n");
      out.write("\t\t\t\t\thref=\"http://sh.cyberpolice.cn/infoCategoryListAction.do?act=initjpg\"\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath() );
      out.write("/icbc/investmentlinked/global/police.png\"></a>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;<a target=\"_blank\" href=\"http://www.zx110.org/\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath() );
      out.write("/icbc/investmentlinked/global/zx110.png\"></a>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;<a target=\"_blank\"\r\n");
      out.write("\t\t\t\t\thref=\"http://www.sgs.gov.cn/lz/licenseLink.do?method=licenceView&entyId=20120801110827275\"><img\r\n");
      out.write("\t\t\t\t\tborder=\"0\" src=\"");
      out.print(request.getContextPath() );
      out.write("/icbc/investmentlinked/global/icon.gif\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"float: left; line-height: 60px;\">\r\n");
      out.write("\t\t\t\t<a>版权所有</a>&nbsp;&nbsp;&nbsp;&nbsp;<a>工银安盛人寿</a>&nbsp;&nbsp;&nbsp;&nbsp;<a>沪ICP备10003475号</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
