/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-04-12 09:59:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.icbc.investmentlinked.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/tlds/dict.tld", Long.valueOf(1397242678135L));
    _jspx_dependants.put("/WEB-INF/tlds/fn.tld", Long.valueOf(1397242676826L));
    _jspx_dependants.put("/WEB-INF/tlds/fmt.tld", Long.valueOf(1397242678139L));
    _jspx_dependants.put("/icbc/investmentlinked/page/../../../common/page/common.jsp", Long.valueOf(1397272927329L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1397242678131L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/css/niceValidate/jquery.validator.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<!-- \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/jquery.validator.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/zh_CN.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("<!--  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/validate/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/validate/additional-methods.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/validate/messages_zh.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/jquery.lightbox_me.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/css/login.css\">\r\n");
      out.write("\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML> \r\n");
      out.write("<html>\r\n");
      out.write("  <head lang=\"en\">\r\n");
      out.write("    <title>工银安盛人寿保险有限公司</title>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"width:100%;\">\r\n");
      out.write("\t<div style=\"width:795px;margin:0 auto;\">\r\n");
      out.write("\t\t<div style=\"font-size:18px;color:#202020;font-family: SimSun;font-weight:bold;margin-top:20px;\">健康告知，请您确认是否符合以下情况：</div>\r\n");
      out.write("\t\t<div style=\"font-size:14px;color:#707070;font-family: SimSun;margin-top:20px;line-height:180%;\">\r\n");
      out.write("\t\t 1.保险人非从事诸如军事人员、刑事执法人员、潜水员、飞机轮船机组人员、全职的驾驶摩托车的快件投递员、采矿人员、与有毒有害气体或物质接触的任何职业等危险职业，未参加并将不参加赛车、竞马、登山、攀岩、其它危险性运动<br>\r\n");
      out.write("\t\t 2.被保险人没有智能障碍、失明、聋哑、跛行、脊柱或胸廓畸形、四肢缺损或畸形等任何身体残疾<br>\r\n");
      out.write("\t\t 3.被保险人未患有或曾经患有精神疾病、脑血管意外（脑出血、脑梗塞）、瘫痪、冠心病、心肌梗死、高血压（血压超过150/100mmHg）、癌症。\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"font-size:18px;color:#202020;font-family: SimSun;font-weight:bold;margin-top:20px;\">以下投保注意事项，请您关注：</div>\r\n");
      out.write("\t\t<div style=\"font-size:14px;color:#707070;font-family: SimSun;margin-top:20px;line-height:180%;\">\r\n");
      out.write("\t\t1、本（电子）投保单为投保人与保险公司所订立保险合同的组成部分，在填写投保单之前，请仔细阅读投保单的内容并确认条款含义。<br>\r\n");
      out.write("\t\t2、投保单的填写：本投保单应由投保人根据投保流程使用属于自己的注册用户名与密码，并亲自填写各项内容。且投保填写内容已征得被保险人同意。<br>\r\n");
      out.write("\t\t3、告知义务：依据我国《保险法》的规定，投保人、被保险人在投保时，应对投保单、体检报告各项内容以及保险人指定医院检查被保险人健康时的各项询问按规定如实详细告知。否则保险人有权依法解除保险合同，并对于保险合同解除前发生的保险事故不负任何责任。所有告知事项均以提交的电子或书面告知为准，口头告知无效。<br>\r\n");
      out.write("\t\t4、身故受益人：受益人在未指定情况下，视为法定继承人。<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"font-size:18px;color:#202020;font-family: SimSun;font-weight:bold;margin-top:20px;\">投保人声明：</div>\r\n");
      out.write("\t\t<div style=\"font-size:14px;color:#707070;font-family: SimSun;margin-top:20px;line-height:180%;\">\r\n");
      out.write("\t\t1、本投保人兹申明以上各项内容填写属实，已征得被保险人同意，并认可保险金额。被保险人仅限1-4类职业人员，若被保险人从事5类及5类以上职业或拒保职业的工作要求出险理赔，则不属于保险责任范围。（查看职业分类表和拒保职业分类表，职业类别不明请咨询4008688888）。<br>\r\n");
      out.write("\t\t2、本人已认真阅读并理解 保险条款 、投保须知 和 投保声明书 的全部内容，且同意将电子保单发出之日的次日视为客户签收日。同意如发生有关网上投保险种、保险金额等方面的分歧，以贵公司的电子记录凭证等数据电文作为判断本保险合同的唯一合法有效凭证，该凭证具有完全证据效力。<br>\r\n");
      out.write("\t\t3、根据《中华人民共和国合同法》第十一条规定，数据电文是合法的合同表现形式。本人接受以太平人寿保险有限公司提供的电子保单作为本投保书成立的合法有效凭证，具有完全证据效力。<br>\r\n");
      out.write("\t\t4、     在中国法律允许或要求范围内，本人同意或授权承保公司将保单和个人信息提供给意外险信息平台做合理利用及短信服务。<br>\r\n");
      out.write("\t\t5、     本人已经阅读并了解太平人寿所有分支机构包含以下地区：北京市、上海市、广东省、天津市、重庆市、江苏省、浙江省、福建省、湖南省、湖北省、河南省、河北省、山东省、山西省、安徽省、江西<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /icbc/investmentlinked/page/../../../common/page/common.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /icbc/investmentlinked/page/../../../common/page/common.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
