/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-04-15 05:49:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.icbc.investmentlinked.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import cn.com.sinosoft.core.hibernate.Page2;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/tlds/dict.tld", Long.valueOf(1397242678135L));
    _jspx_dependants.put("/WEB-INF/tlds/fn.tld", Long.valueOf(1397242676826L));
    _jspx_dependants.put("/WEB-INF/tlds/fmt.tld", Long.valueOf(1397242678139L));
    _jspx_dependants.put("/icbc/investmentlinked/page/../../../common/page/common.jsp", Long.valueOf(1397430122165L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1397242678131L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/css/niceValidate/jquery.validator.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<!-- \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/jquery.validator.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/zh_CN.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("<!--  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/validate/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/validate/additional-methods.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/js/validate/messages_zh.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/jquery.lightbox_me.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/css/login.css\">\r\n");
      out.write("\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML> \r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("<TITLE>工银安盛人寿保险有限公司</TITLE>\r\n");
      out.write("<META name=\"description\" content=\"工银安盛人寿官方网站提供最新公司动态，为您提供有关工银安盛人寿近期新闻信息、活动资讯、产品服务等的第一手资讯\">\r\n");
      out.write("<script type=\"text/javascript\"  src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/insure.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/date/WdatePicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"  src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/investment.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"  src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/json2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/date.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/policyDownload.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/js/order.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/css/membercenter.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/css/order.css\">\r\n");
      out.write("<script type=\"text/javascript\">\tvar ctx = '");
      out.print(request.getContextPath());
      out.write("';</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin:0 auto;\">\r\n");
      out.write("<div id=\"baseWrapper\">\r\n");
      out.write("\t<div id=\"content-whole-mid\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"content\" style=\"background-color:#ffffff;\">\r\n");
      out.write("\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/\" style=\"margin-left:15px;\">在线商城首页</a><font\tcolor=\"#7f7f7f\">&gt;</font><a href=\"#\">我的融e保</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"float:right;width:250px;display:block;height:30px;\"></div>\r\n");
      out.write("\t\t\t<div class=\"leftpanel00\">\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftPanel0.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"detail\">\r\n");
      out.write("\t\t\t\t<!-- 中间订单查询 开始 -->\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-left:5px;width: 670px;margin-bottom: 5px;margin-top: 5px\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"allbutton\" style=\"font-family: 宋体;font-size: 14px;font-weight: bold;border-bottom: 1px solid red;background-image: url('");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/images/quan.jpg');\" width='124' height=\"38\" onMouseOver=allCancelSwtTab(this)><center>&nbsp;</center></td>\r\n");
      out.write("\t\t\t\t\t<td id=\"unbutton\" style=\"font-family: 宋体;font-size: 14px;font-weight: bold;border-bottom: 1px solid red\"  width='124' height=\"38\" onMouseOver=cancelSwtTab(this)><center>未完成订单</center></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border-bottom: 1px solid red\">&nbsp;</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\t\t\t\r\n");
      out.write("\t\t\t<div id=\"allOrder\">\t\t\t\r\n");
      out.write("\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" style=\"border:1px solid #c7bc9c;margin-left:5px;width: 670px;\">\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr height=\"25\" align=\"center\" bgcolor=\"#c7bc9c\">\r\n");
      out.write("\t\t\t\t\t<th width=\"25%\" class=\"thtop\">订单号</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\" class=\"thtop\">交易时间</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">投保份数</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">订单金额</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">订单状态</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">订单详情</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">后维操作</th>\r\n");
      out.write("\t\t\t \t</tr>\t\t\t  \r\n");
      out.write("\t\t\t\t  ");

				  	String timeflag  = (String)request.getAttribute("timeflag");
				  	Page2 page2  = (Page2)request.getAttribute("page2");
				  	List orderAll = page2.getResult();
				  	String paystatus = "";
				  	for(int i =0;i<orderAll.size();i++){
				  		Object[] obj =(Object[])orderAll.get(i);
				  
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t\t\t<tr height=\"25\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\" style=\"font-family: Arial;font-size: 12px;\">");
      out.print(obj[0]==null?"":obj[0]);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\" style=\"color: #7f7f7f\">");
      out.print(obj[1]==null?"":obj[1]);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\">");
      out.print(obj[2]==null?"":obj[2]);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\"><script>document.write(Number('");
      out.print(obj[3]==null?"":obj[3]);
      out.write("').toFixed(2));</script> </td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(obj[4].equals("0")){
								paystatus = "未支付";
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<font color=\"red\">");
      out.print(paystatus);
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t");
}else if(obj[4].equals("1")){paystatus = "已支付";
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(paystatus);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
}else{paystatus="已逾期";
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(paystatus);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\"  onmouseover=\"this.style.cursor='hand'\"><a href=\"javascript:orderDetailExt('");
      out.print(obj[5]);
      out.write("')\">查看详情</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(obj[4].equals("0")){
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if(timeflag.equals(obj[1]==null?"":obj[1])){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:conPay('");
      out.print(obj[5]);
      out.write("')\">继续支付</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"color: gray\"><a href=\"javascript:chedan('");
      out.print(obj[5]);
      out.write("')\" style=\"color: gray\">撤单</a></font>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
}else if(obj[4].equals("1")){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"color: gray\"><a href=\"javascript:policyDownload('");
      out.print(obj[6]);
      out.write("')\" style=\"color: gray\">保单下载</a></font>\r\n");
      out.write("\t\t\t\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=\"#7f7f7f\">-</font>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
	} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div style=\"margin-top: 10px;width: 680px;float:right;margin-right:20px;\">\r\n");
      out.write("\t\t\t\t\t<span style=\"float: left;margin-left:460px;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:;\" style=\"float:left;margin-right:12px;\">共");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page2.currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page2.pageCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("页</a>\r\n");
      out.write("\t\t\t\t\t\t<font style=\"float:left;\"><a href=\"javascript:goSearch('1')\" style=\"margin:0 2px;\">首页</a></font>\r\n");
      out.write("\t\t\t\t\t\t<font style=\"float:left;\" color=\"#7f7f7f\">|<a style=\"margin:0 2px;\" href=\"javascript:goSearch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page2.beforePage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">上一页</a></font>\r\n");
      out.write("\t\t\t\t\t\t<font style=\"float:left;\" color=\"#7f7f7f\">|<a style=\"margin:0 2px;\" href=\"javascript:goSearch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page2.nextPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">下一页</a></font>\r\n");
      out.write("\t\t\t\t\t\t<font style=\"float:left;\" color=\"#7f7f7f\">|<a style=\"margin:0 2px;\" href=\"javascript:goSearch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page2.pageCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">尾页</a></font>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t<div id=\"unAllOrder\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" style=\"border:1px solid #c7bc9c;margin-left:5px;width: 670px;\">\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr height=\"25\" align=\"center\" bgcolor=\"#c7bc9c\">\r\n");
      out.write("\t\t\t\t\t<th width=\"25%\" class=\"thtop\">订单号</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\" class=\"thtop\">交易时间</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">投保份数</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">订单金额</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">订单状态</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">订单详情</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"14%\" class=\"thtop\">后维操作</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t  \t ");

			  		Page2 page3  = (Page2)request.getAttribute("page3");
			  		List orderUn = page3.getResult();
			  		for(int i =0;i<orderUn.size();i++){
			  			Object[] obj =(Object[])orderUn.get(i);
			  	
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr height=\"25\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\" style=\"font-family: Arial;font-size: 12px;\">");
      out.print(obj[0]==null?"":obj[0]);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\" style=\"color: #7f7f7f\">");
      out.print(obj[1]==null?"":obj[1]);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\">");
      out.print(obj[2]==null?"":obj[2]);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\"><script>document.write(Number('");
      out.print(obj[3]==null?"":obj[3]);
      out.write("').toFixed(2));</script> </td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(obj[4].equals("0")){
									paystatus = "未支付";
							}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<font color=\"red\">");
      out.print(paystatus);
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\" onmouseover=\"this.style.cursor='hand'\"><a href=\"javascript:orderDetailExt('");
      out.print(obj[5]);
      out.write("')\">查看详情</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"borderk\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(obj[4].equals("0")){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if(timeflag.equals(obj[1]==null?"":obj[1])){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:conPay('");
      out.print(obj[5]);
      out.write("')\">继续支付</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:chedan('");
      out.print(obj[5]);
      out.write("')\" style=\"color:gray\">撤单</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div style=\"margin-top: 10px;width: 680px;float:right;margin-right:20px;\">\r\n");
      out.write("\t\t\t\t<span style=\"float: left;margin-left:460px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" style=\"float:left;margin-right:12px;\">共");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page3.currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page3.pageCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("页</a>\r\n");
      out.write("\t\t\t\t\t<font style=\"float:left;\"><a style=\"margin:0 2px;\" href=\"javascript:goSearch2('1')\">首页</a></font>\r\n");
      out.write("\t\t\t\t\t<font style=\"float:left;\" color=\"#7f7f7f\">|<a style=\"margin:0 2px;\" href=\"javascript:goSearch2('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page3.beforePage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">上一页</a></font>\r\n");
      out.write("\t\t\t\t\t<font style=\"float:left;\" color=\"#7f7f7f\">|<a style=\"margin:0 2px;\" href=\"javascript:goSearch2('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page3.nextPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">下一页</a></font>\r\n");
      out.write("\t\t\t\t\t<font style=\"float:left;\" color=\"#7f7f7f\">|<a style=\"margin:0 2px;\" href=\"javascript:goSearch2('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page3.pageCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">尾页</a></font>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 中间订单查询 结束 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"leftpanel01\">\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftPanel01.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<DIV id=\"homeBanner\" style=\"margin-top:30px;padding: 10px 0px 9px 13px; width: 960px;  overflow: hidden;margin-left:4px;\">\t\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "homeBanner.jsp", out, false);
      out.write("\r\n");
      out.write("\t</DIV>\r\n");
      out.write("</div>\r\n");
      out.write("<DIV style=\"margin:23px auto 0px; padding: 0px 0px 23px; width: 985px;\"></DIV>\r\n");
      out.write("<div id=\"footerWrapper\" style=\"width: 100%; height:67px;float:left; \">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--订单详情 开始-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"light\" class=\"white_content\">\r\n");
      out.write("\t\r\n");
      out.write("\t  <div style=\"float:right ;\"><a href=\"javascript:void(0)\" onclick=\"hide('light')\">\r\n");
      out.write("\t\t    <img src=\"");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/images/colsebutton.png\"></a>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t\t\r\n");
      out.write("      <div id=\"orderDetail\" style=\"background-color:#ffffff;padding:40px; \"> \r\n");
      out.write("      \r\n");
      out.write("\t\t\t<div id=\"Layer2\">电子保单预览</div>\t\t\t\r\n");
      out.write("\t\t\t<div id=\"Layer3\">\r\n");
      out.write("\t\t\t  <table width=\"911\" border=\"0\">\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td width=\"109\"><strong>保单合同编号</strong></td>\r\n");
      out.write("\t\t\t      <td width=\"196\" id =\"policycode\"></td>\r\n");
      out.write("\t\t\t      <td width=\"148\"><strong>保险合同生效日期</strong></td>\r\n");
      out.write("\t\t\t      <td width=\"138\" id=\"takeEffecttime\"></td>\r\n");
      out.write("\t\t\t      <td width=\"77\"><strong>货币单价</strong></td>\r\n");
      out.write("\t\t\t      <td width=\"217\" >人民币</td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"Layer4\">\r\n");
      out.write("\t\t\t  <table width=\"915\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t    <tr bgcolor=\"#c7bc9c\">\r\n");
      out.write("\t\t\t      <td height=\"25\" colspan=\"8\"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;投保人</strong></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" style=\"border-left: 1px solid #cccccc;\" width=\"8%\" height=\"24%\">姓名:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" width=\"15%\" id=\"appName\"></td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" width=\"10%\">性别:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" width=\"15%\" id=\"appSex\"></td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" width=\"10%\">出生日期:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" width=\"15%\" id=\"appBirthday\"></td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" width=\"10%\">投保地区:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" style=\"border-right: 1px solid #cccccc;\" id=\"appArea\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" style=\"border-left: 1px solid #cccccc;\" height=\"24%\">手机:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" id=\"appMobile\"></td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" >固定电话:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" id=\"appPhone\"></td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\">电子邮箱:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" id=\"appEmail\"></td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\">邮编:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" style=\"border-right: 1px solid #cccccc;\" id=\"appZipcode\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" style=\"border-left: 1px solid #cccccc;\" height=\"28%\" id=\"appIdType\">身份证:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" id=\"appIdNo\"></td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\">联系人地址:</td>\r\n");
      out.write("\t\t\t      <td class=\"tdsy\" style=\"border-right: 1px solid #cccccc;\" colspan=\"5\" id=\"appAddress\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"bbxr\">被保险人</div>\r\n");
      out.write("\t\t\t<div id=\"bbxrVal\"><span style=\"display:none;\" id=\"insEq\">与投保人为同一人</span>\r\n");
      out.write("\t\t\t\t<table height=\"100%\" cellpadding=\"0\" cellspacing=\"0\" id=\"insTable\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"70\">姓名:</td><td width=\"137px\" id=\"insName\"></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"70\">性别:</td><td width=\"137px\"  id=\"insSex\"></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"70\" id=\"insIdType\">身份证:</td><td width=\"229px\" id=\"insIdNo\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"benefited\" style=\"height:25\">受益人\t</div>\r\n");
      out.write("\t\t\t<div style=\"display: none; height:25\" id=\"benFlagFd\">\r\n");
      out.write("\t\t\t\t法定受益人\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"benefitedVal\" style=\"height: 40px;\">\r\n");
      out.write("\t\t\t\t<table style=\"width: 100%;\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tdsy\">姓名:</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tdsy\" id=\"benName\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tdsy\">性别:</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tdsy\" id=\"benSex\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tdsy\" id=\"benIdType\">身份证:</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tdsy\" id=\"benIdNo\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>与被保人关系:</td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"benGx\" colspan=\"5\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"nearly\">\r\n");
      out.write("\t\t\t  <table width=\"916\" height=\"108\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" >\r\n");
      out.write("\t\t\t    <tr height=\"25\" bgcolor=\"#c7bc9c\">\r\n");
      out.write("\t\t\t      <td colspan=\"2\"><strong>险种名称</strong></td>\r\n");
      out.write("\t\t\t      <td width=\"10%\" class=\"borderk\"><strong>保险金额</strong></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td width=\"8%\" class=\"borderk\">主险</td>\r\n");
      out.write("\t\t\t      <td width=\"32%\" class=\"borderk\" id=\"riskName\"></td>\r\n");
      out.write("\t\t\t      <td class=\"borderk\" id=\"riskAmount\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t  </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"pay\">\r\n");
      out.write("\t\t\t  <table height=\"40px\" width=\"904\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td width=\"10%\"><strong>交费方式</strong>：</td>\r\n");
      out.write("\t\t\t      <td width=\"10%\" id=\"payType\"></td>\r\n");
      out.write("\t\t\t      <td width=\"18%\"><strong>本期保险缴费合计：</strong></td>\r\n");
      out.write("\t\t\t      <td width=\"15%\" id=\"sumAmount\"></td>\r\n");
      out.write("\t\t\t      <td width=\"12%\"><strong>保险期间：</strong></td>\r\n");
      out.write("\t\t\t      <td><span id=\"tremStart\"></span>至<span id=\"tremEnd\"></span>止</td>\r\n");
      out.write("\t\t\t    </tr>\t\t\t    \r\n");
      out.write("\t\t\t  </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!--订单详情 END-->\t\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function cancelSwtTab(tag){\r\n");
      out.write("\tvar allbt=document.getElementById('allbutton');\r\n");
      out.write("\tvar un=document.getElementById('unAllOrder');\r\n");
      out.write("\tvar all=document.getElementById('allOrder');\r\n");
      out.write("\tun.style.display='block';\r\n");
      out.write("\tall.style.display='none';\r\n");
      out.write("\ttag.style.background='url(");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/images/weiwancheng.jpg)';\r\n");
      out.write("\tallbt.style.background='url(\"\")';\r\n");
      out.write("\ttag.innerHTML=\"\";\r\n");
      out.write("\tallbt.innerHTML='<center>全部订单</center>';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function allCancelSwtTab(tag){\r\n");
      out.write("\tvar unbt=document.getElementById('unbutton');\r\n");
      out.write("\tvar un=document.getElementById('unAllOrder');\r\n");
      out.write("\tvar all=document.getElementById('allOrder');\r\n");
      out.write("\tun.style.display='none';\r\n");
      out.write("\tall.style.display='block';\r\n");
      out.write("\ttag.style.background='url(");
      out.print(request.getContextPath());
      out.write("/icbc/investmentlinked/images/quan.jpg)';\r\n");
      out.write("\tunbt.style.background='url(\"\")';\r\n");
      out.write("\ttag.innerHTML=\"\";\r\n");
      out.write("\tunbt.innerHTML='<center>未完成订单</center>';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function hide(tag){\r\n");
      out.write("\t $(\"#light\").trigger('close');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function conPay(orderno){\r\n");
      out.write("\twindow.location=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/continuePay?orderno=\"+orderno;\r\n");
      out.write("}\r\n");
      out.write("function chedan(orderno){\r\n");
      out.write("\tif(confirm(\"您确定要撤销该订单吗?\")){\r\n");
      out.write("\t\twindow.location=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icbc/investmentlinked/payBack?orderno=\"+orderno;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /icbc/investmentlinked/page/../../../common/page/common.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /icbc/investmentlinked/page/../../../common/page/common.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
