/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-06-18 10:58:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class investmentvalue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
HashMap<String,String>[] investments = (HashMap[])request.getAttribute("investments");
for(HashMap<String,String> investment:investments){
	if(investment.get("rate") != "" && investment.get("rate") != null && investment.get("rate").endsWith("%")){
		String[] temp = investment.get("rate").split("[.]");
		investment.put("rate", temp[0]+"%");
	}
}

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>保单详情</title>\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../global/css/common.css\" type=\"text/css\"></link>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../global/css/all.css\" type=\"text/css\"></link>\r\n");
      out.write("  \t<!-- init page scale-->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, target-densitydpi=240,initial-scale=0.667, minimum-scale=0.667, maximum-scale=0.667, user-scalable=0\" id=\"viewport\">\r\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\"/>\r\n");
      out.write("  </head>\r\n");
      out.write("   <style>\r\n");
      out.write("\t\t.txt1{font-size: 1.3em;}\r\n");
      out.write("\t.txt2{font-size: 1.0em;}\r\n");
      out.write("\t.txt3{font-size: 0.9em;}\r\n");
      out.write("\t.txt4{font-size: 0.8em;}\r\n");
      out.write("\t.txt5{font-size: 0.7em;}\r\n");
      out.write("\t\t@media only screen and (max-width: 960px) {\r\n");
      out.write("\t\t.txt1{font-size: 1.2em;}\r\n");
      out.write("\t\t.txt2{font-size: 0.9em;}\r\n");
      out.write("\t\t.txt3{font-size: 0.7em;}\r\n");
      out.write("\t\t.txt4{font-size: 0.7em;}\r\n");
      out.write("\t\t.txt5{font-size: 0.6em;}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t@media only screen and (max-width: 640px) {\r\n");
      out.write("\t\t.txt1{font-size:1.1em;}\r\n");
      out.write("\t\t.txt2{font-size: 0.8em;}\r\n");
      out.write("\t\t.txt3{font-size: 0.6em;}\r\n");
      out.write("\t\t.txt4{font-size: 0.6em;}\r\n");
      out.write("\t\t.txt5{font-size: 0.5em;}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t@media only screen and (max-width: 480px) {\r\n");
      out.write("\t\t.title1{font-size: 1.0em;}\r\n");
      out.write("\t\t.txt2{font-size: 0.7em;}\r\n");
      out.write("\t\t.txt3{font-size: 0.5em;}\r\n");
      out.write("\t\t.txt4{font-size: 0.5em;}\r\n");
      out.write("\t\t.txt5{font-size: 0.4em;}\r\n");
      out.write("\t}\r\n");
      out.write("\t.table tr td {padding-top:10px;padding-bottom:10px;}\r\n");
      out.write("  </style>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  \t<div class=\"header\">\r\n");
      out.write("    \t<div>\r\n");
      out.write("\t    \t<div class=\"headertitle\">保单详情</div>\r\n");
      out.write("\t    \t<div class=\"clear\"></div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"clear\"></div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \t<div class=\"content\">\r\n");
      out.write("    \t\t<div class=\"tablehead\">\r\n");
      out.write("    \t\t\t<div class=\"borderleft\"></div>\r\n");
      out.write("    \t\t\t<div class=\"borderright\">\r\n");
      out.write("    \t\t\t\t<div>\r\n");
      out.write("    \t\t\t\t\t<div class=\"titleimgdiv\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t<span class=\"titlecontent black txt1\">保单投资信息</span>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t<div class=\"tablestyle\">\r\n");
      out.write("    \t\t<table class=\"table txt1\"style=\"line-height:30px;\">\r\n");
      out.write("    \t\t\t<tr>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc;text-align: center;\" class=\"firstcolumn1\">投资账户名称</td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc\" class=\"investmentvaluetable1\">实际投资分配比例</td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc\" class=\"investmentvaluetable1\">投资单位数量</td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc\" class=\"investmentvaluetable1\">卖出价</td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc\" class=\"investmentvaluetable1\">投资单位价格日期</td>\r\n");
      out.write("    \t\t\t\t<td class=\"investmentvaluetable1\">投资账户价值</td>  \t\t\t\t\r\n");
      out.write("    \t\t\t</tr>\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t");
 for(HashMap hashmap:investments){
    				if("0.00".equals(hashmap.get("units"))){
    					continue;
    				}else{
    			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("    \t\t\t\t<td style=\"border-top: 1px dashed #dcdbdc;height:0;padding:0;\"></td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-top: 1px dashed #dcdbdc;height:0;padding:0;\"></td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-top: 1px dashed #dcdbdc;height:0;padding:0;\"></td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-top: 1px dashed #dcdbdc;height:0;padding:0;\"></td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-top: 1px dashed #dcdbdc;height:0;padding:0;\"></td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-top: 1px dashed #dcdbdc;height:0;padding:0;\"></td>\r\n");
      out.write("    \t\t\t</tr>\r\n");
      out.write("    \t\t\t<tr>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc\" class=\"investmentsecondcolumn\">");
      out.print(hashmap.get("investmentName") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc\" class=\"investmentsecondcolumn\">");
      out.print(hashmap.get("rate") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc\" class=\"investmentsecondcolumn\">");
      out.print(hashmap.get("units") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc\" class=\"investmentsecondcolumn\">");
      out.print(hashmap.get("price") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t<td style=\"border-right:1px solid #dcdcdc\" class=\"investmentsecondcolumn\">");
      out.print(hashmap.get("priceDate") );
      out.write("</td>    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<td class=\"investmentsecondcolumn\">");
      out.print(hashmap.get("value") );
      out.write("</td>\r\n");
      out.write("    \t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("    \t\t\t");
 }}
      out.write("\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t</table>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div style=\"height: 50px;\"></div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"clear\"></div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
